In [1]:
import pandas as pd
import numpy as np

## Med DF

In [7]:
med_df = pd.read_csv('medical_clean.csv')
med_df.columns = med_df.columns.str.lower()
med_df.head()

,caseorder,customer_id,interaction,uid,city,state,county,zip,lat,lng,...,totalcharge,additional_charges,item1,item2,item3,item4,item5,item6,item7,item8
0,1,C412403,8cd49b13-f45a-4b47-a2bd-173ffa932c2f,3a83ddb66e2ae73798bdf1d705dc0932,Eva,AL,Morgan,35621,34.34960,-86.72508,...,3726.702860,17939.403420,3,3,2,2,4,3,3,4
1,2,Z919181,d2450b70-0337-4406-bdbb-bc1037f1734c,176354c5eef714957d486009feabf195,Marianna,FL,Jackson,32446,30.84513,-85.22907,...,4193.190458,17612.998120,3,4,3,4,4,4,3,3
2,3,F995323,a2057123-abf5-4a2c-abad-8ffe33512562,e19a0fa00aeda885b8a436757e889bc9,Sioux Falls,SD,Minnehaha,57110,43.54321,-96.63772,...,2434.234222,17505.192460,2,4,4,4,3,4,3,3
3,4,A879973,1dec528d-eb34-4079-adce-0d7a40e82205,cd17d7b6d152cb6f23957346d11c3f07,New Richland,MN,Waseca,56072,43.89744,-93.51479,...,2127.830423,12993.437350,3,5,5,3,4,5,5,5
4,5,C544523,5885f56b-d6da-43a3-8760-83583af94266,d2f0425877b10ed6bb381f3e2579424a,West Point,VA,King William,23181,37.59894,-76.88958,...,2113.073274,3716.525786,2,1,3,3,5,3,4,3

## State Expenditure DF

In [5]:
state_df = pd.read_csv('state_expenditure.csv')
state_df.columns = state_df.columns.str.lower()
state_df.head()

           state spending_per_capita
0  United States           $10191.00
1        Alabama            $9280.00
2         Alaska           $13642.00
3        Arizona            $8756.00
4       Arkansas            $9338.00

Notes
The Centers for Medicare and Medicaid Services (CMS) Office of the Actuary produces Health Expenditures by State of Residence and Health Expenditures by State of Provider every five years. The State Health Expenditure Accounts are a subcomponent of the National Health Expenditure Accounts (NHEA), the official government estimates of health spending in the United States.  

Additional information on data and methods is available [here.](http://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/NationalHealthExpendData/NationalHealthAccountsStateHealthAccountsResidence.html)

Sources
Centers for Medicare & Medicaid Services, Office of the Actuary, National Health Statistics Group. [National Health Expenditure Data: Health Expenditures by State of Residence](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/NationalHealthExpendData/NationalHealthAccountsStateHealthAccountsResidence.html), August 2022.

Definitions
*Health Spending Per Capita* includes spending for all privately and publicly funded personal health care services and products (hospital care, physician services, nursing home care, prescription drugs, etc.) by state of residence (aggregate spending divided by population). Hospital spending is included and reflects the total net revenue (gross charges less contractual adjustments, bad debts, and charity care). Costs such as insurance program administration, research, and construction expenses are not included in this total.

In [6]:
print(f'Medical dataframe has {len(sorted(med_df.state.unique()))} unique state entries')
print(f'State Expenditure dataframe has {len(sorted(state_df.state.unique()))} unique state entries')

Medical dataframe has 52 unique state entries
State Expenditure dataframe has 52 unique state entries

In [12]:
##merge
# State abbreviation-to-name mapping
state_dict = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'DC': 'District of Columbia',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming'
}

# Convert state abbreviations to full names
med_df['state'] = med_df['state'].map(state_dict)
med_df.head().T

,0,1,2,3,4
caseorder,1,2,3,4,5
customer_id,C412403,Z919181,F995323,A879973,C544523
interaction,8cd49b13-f45a-4b47-a2bd-173ffa932c2f,d2450b70-0337-4406-bdbb-bc1037f1734c,a2057123-abf5-4a2c-abad-8ffe33512562,1dec528d-eb34-4079-adce-0d7a40e82205,5885f56b-d6da-43a3-8760-83583af94266
uid,3a83ddb66e2ae73798bdf1d705dc0932,176354c5eef714957d486009feabf195,e19a0fa00aeda885b8a436757e889bc9,cd17d7b6d152cb6f23957346d11c3f07,d2f0425877b10ed6bb381f3e2579424a
city,Eva,Marianna,Sioux Falls,New Richland,West Point
state,Alabama,Florida,South Dakota,Minnesota,Virginia
county,Morgan,Jackson,Minnehaha,Waseca,King William
zip,35621,32446,57110,56072,23181
lat,34.3496,30.84513,43.54321,43.89744,37.59894
lng,-86.72508,-85.22907,-96.63772,-93.51479,-76.88958
population,2951,11303,17125,2162,5287
area,Suburban,Urban,Suburban,Suburban,Rural
timezone,America/Chicago,America/Chicago,America/Chicago,America/Chicago,America/New_York
job,"Psychologist, sport and exercise",Community development worker,Chief Executive Officer,Early years teacher,Health promotion specialist
children,1,3,3,0,1
age,53,51,53,78,22
income,86575.93,46805.99,14370.14,39741.49,1209.56
marital,Divorced,Married,Widowed,Married,Widowed
gender,Male,Female,Female,Male,Female
readmis,No,No,No,No,No
vitd_levels,19.141466,18.940352,18.057507,16.576858,17.439069
doc_visits,6,4,4,4,5
full_meals_eaten,0,2,1,1,0
vitd_supp,0,1,0,0,2
soft_drink,No,No,No,No,Yes
initial_admin,Emergency Admission,Emergency Admission,Elective Admission,Elective Admission,Elective Admission
highblood,Yes,Yes,Yes,No,No
stroke,No,No,No,Yes,No
complication_risk,Medium,High,Medium,Medium,Low
overweight,No,Yes,Yes,No,No
arthritis,Yes,No,No,Yes,No
diabetes,Yes,No,Yes,No,No
hyperlipidemia,No,No,No,No,Yes
backpain,Yes,No,No,No,No
anxiety,Yes,No,No,No,No
allergic_rhinitis,Yes,No,No,No,Yes
reflux_esophagitis,No,Yes,No,Yes,No
asthma,Yes,No,No,Yes,No
services,Blood Work,Intravenous,Blood Work,Blood Work,CT Scan
initial_days,10.58577,15.129562,4.772177,1.714879,1.254807
totalcharge,3726.70286,4193.190458,2434.234222,2127.830423,2113.073274
additional_charges,17939.40342,17612.99812,17505.19246,12993.43735,3716.525786
item1,3,3,2,3,2
item2,3,4,4,5,1
item3,2,3,4,5,3
item4,2,4,4,3,3
item5,4,4,3,4,5
item6,3,4,4,5,3
item7,3,3,3,5,4
item8,4,3,3,5,3

In [13]:
print(f'State DF is missing: {set(med_df.state.unique()).difference(set(state_df.state.unique()))}')

State DF is missing: {'Puerto Rico'}

In [14]:
print(f'Medical DF is missing: {set(state_df.state.unique()).difference(set(med_df.state.unique()))}')

Medical DF is missing: {'United States'}

In [19]:
# drop united states from state_df to prep merge
state_df = state_df.loc[state_df.state!='United States']

In [24]:
state_df

                   state spending_per_capita
1                Alabama            $9280.00
2                 Alaska           $13642.00
3                Arizona            $8756.00
4               Arkansas            $9338.00
5             California           $10299.00
6               Colorado            $8583.00
7            Connecticut           $12489.00
8               Delaware           $12899.00
9   District of Columbia           $14381.00
10               Florida            $9865.00
11               Georgia            $8758.00
12                Hawaii           $10291.00
13                 Idaho            $8148.00
14              Illinois           $10190.00
15               Indiana           $10517.00
16                  Iowa            $9789.00
17                Kansas            $9408.00
18              Kentucky           $10257.00
19             Louisiana           $10515.00
20                 Maine           $12077.00
21              Maryland           $10839.00
22         Massachusetts           $13319.00
23              Michigan            $9897.00
24             Minnesota           $10846.00
25           Mississippi            $9394.00
26              Missouri            $9921.00
27               Montana           $10212.00
28              Nebraska           $10514.00
29                Nevada            $8348.00
30         New Hampshire           $11793.00
31            New Jersey           $11868.00
32            New Mexico            $8902.00
33              New York           $14007.00
34        North Carolina            $8917.00
35          North Dakota           $11301.00
36                  Ohio           $10478.00
37              Oklahoma            $9444.00
38                Oregon           $10071.00
39          Pennsylvania           $11603.00
40          Rhode Island           $11694.00
41        South Carolina            $8766.00
42          South Dakota           $12495.00
43             Tennessee            $9336.00
44                 Texas            $8406.00
45                  Utah            $7522.00
46               Vermont           $12756.00
47              Virginia            $9195.00
48            Washington            $9265.00
49         West Virginia           $12769.00
50             Wisconsin            $9982.00
51               Wyoming           $10989.00

In [31]:
state_df['spending_per_capita'] = state_df.spending_per_capita.str.replace('$', '', regex=False)
state_df['spending_per_capita'] = state_df.spending_per_capita.str.replace('.00', '', regex=False)
state_df['spending_per_capita'] = state_df.spending_per_capita.astype('int64')

In [37]:
print(f'Shape of med_df {med_df.shape}')
merged_df = med_df.merge(state_df, on='state', how='left')
print(f'Shape of new merged df {merged_df.shape}')

Shape of med_df (10000, 50)
Shape of new merged df (10000, 51)

In [45]:
merged_df.to_csv('merged_cleaned_df.csv', index=False)

In [46]:
df = pd.read_csv('merged_cleaned_df.csv')
df.head()

,caseorder,customer_id,interaction,uid,city,state,county,zip,lat,lng,...,additional_charges,item1,item2,item3,item4,item5,item6,item7,item8,spending_per_capita
0,1,C412403,8cd49b13-f45a-4b47-a2bd-173ffa932c2f,3a83ddb66e2ae73798bdf1d705dc0932,Eva,Alabama,Morgan,35621,34.34960,-86.72508,...,17939.403420,3,3,2,2,4,3,3,4,9280.0
1,2,Z919181,d2450b70-0337-4406-bdbb-bc1037f1734c,176354c5eef714957d486009feabf195,Marianna,Florida,Jackson,32446,30.84513,-85.22907,...,17612.998120,3,4,3,4,4,4,3,3,9865.0
2,3,F995323,a2057123-abf5-4a2c-abad-8ffe33512562,e19a0fa00aeda885b8a436757e889bc9,Sioux Falls,South Dakota,Minnehaha,57110,43.54321,-96.63772,...,17505.192460,2,4,4,4,3,4,3,3,12495.0
3,4,A879973,1dec528d-eb34-4079-adce-0d7a40e82205,cd17d7b6d152cb6f23957346d11c3f07,New Richland,Minnesota,Waseca,56072,43.89744,-93.51479,...,12993.437350,3,5,5,3,4,5,5,5,10846.0
4,5,C544523,5885f56b-d6da-43a3-8760-83583af94266,d2f0425877b10ed6bb381f3e2579424a,West Point,Virginia,King William,23181,37.59894,-76.88958,...,3716.525786,2,1,3,3,5,3,4,3,9195.0

In [47]:
df.dtypes

caseorder                int64
customer_id             object
interaction             object
uid                     object
city                    object
state                   object
county                  object
zip                      int64
lat                    float64
lng                    float64
population               int64
area                    object
timezone                object
job                     object
children                 int64
age                      int64
income                 float64
marital                 object
gender                  object
readmis                 object
vitd_levels            float64
doc_visits               int64
full_meals_eaten         int64
vitd_supp                int64
soft_drink              object
initial_admin           object
highblood               object
stroke                  object
complication_risk       object
overweight              object
arthritis               object
diabetes                object
hyperlipidemia          object
backpain                object
anxiety                 object
allergic_rhinitis       object
reflux_esophagitis      object
asthma                  object
services                object
initial_days           float64
totalcharge            float64
additional_charges     float64
item1                    int64
item2                    int64
item3                    int64
item4                    int64
item5                    int64
item6                    int64
item7                    int64
item8                    int64
spending_per_capita    float64
dtype: object

In [2]:
## merged cleaned df
df = pd.read_csv('merged_cleaned_df.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 51 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   caseorder            10000 non-null  int64
 1   customer_id          10000 non-null  object
 2   interaction          10000 non-null  object
 3   uid                  10000 non-null  object
 4   city                 10000 non-null  object
 5   state                10000 non-null  object
 6   county               10000 non-null  object
 7   zip                  10000 non-null  int64
 8   lat                  10000 non-null  float64
 9   lng                  10000 non-null  float64
 10  population           10000 non-null  int64
 11  area                 10000 non-null  object
 12  timezone             10000 non-null  object
 13  job                  10000 non-null  object
 14  children             10000 non-null  int64
 15  age                  10000 non-null  int64
 16  income               10000 non-null  float64
 17  marital              10000 non-null  object
 18  gender               10000 non-null  object
 19  readmis              10000 non-null  object
 20  vitd_levels          10000 non-null  float64
 21  doc_visits           10000 non-null  int64
 22  full_meals_eaten     10000 non-null  int64
 23  vitd_supp            10000 non-null  int64
 24  soft_drink           10000 non-null  object
 25  initial_admin        10000 non-null  object
 26  highblood            10000 non-null  object
 27  stroke               10000 non-null  object
 28  complication_risk    10000 non-null  object
 29  overweight           10000 non-null  object
 30  arthritis            10000 non-null  object
 31  diabetes             10000 non-null  object
 32  hyperlipidemia       10000 non-null  object
 33  backpain             10000 non-null  object
 34  anxiety              10000 non-null  object
 35  allergic_rhinitis    10000 non-null  object
 36  reflux_esophagitis   10000 non-null  object
 37  asthma               10000 non-null  object
 38  services             10000 non-null  object
 39  initial_days         10000 non-null  float64
 40  totalcharge          10000 non-null  float64
 41  additional_charges   10000 non-null  float64
 42  item1                10000 non-null  int64
 43  item2                10000 non-null  int64
 44  item3                10000 non-null  int64
 45  item4                10000 non-null  int64
 46  item5                10000 non-null  int64
 47  item6                10000 non-null  int64
 48  item7                10000 non-null  int64
 49  item8                10000 non-null  int64
 50  spending_per_capita  9957 non-null   float64
dtypes: float64(8), int64(16), object(27)
memory usage: 3.9+ MB

In [4]:
df.dtypes

caseorder                int64
customer_id             object
interaction             object
uid                     object
city                    object
state                   object
county                  object
zip                      int64
lat                    float64
lng                    float64
population               int64
area                    object
timezone                object
job                     object
children                 int64
age                      int64
income                 float64
marital                 object
gender                  object
readmis                 object
vitd_levels            float64
doc_visits               int64
full_meals_eaten         int64
vitd_supp                int64
soft_drink              object
initial_admin           object
highblood               object
stroke                  object
complication_risk       object
overweight              object
arthritis               object
diabetes                object
hyperlipidemia          object
backpain                object
anxiety                 object
allergic_rhinitis       object
reflux_esophagitis      object
asthma                  object
services                object
initial_days           float64
totalcharge            float64
additional_charges     float64
item1                    int64
item2                    int64
item3                    int64
item4                    int64
item5                    int64
item6                    int64
item7                    int64
item8                    int64
spending_per_capita    float64
dtype: object

# EXPLORE & BRAINSTORM

## 1A
- data integrated from two sources
- FOUR different data representations to summarize or display trends
- TWO different interactive controls
- TWO different metrics using data from BOTH SETS

## LAYOUT

**Examples**
- Average healthcare cost per patient vs. state health expenditure
- Correlation between state spending and patient outcomes (e.g., readmission rates, length of stay, or complication risk)

***Trend Analysis***
- Line or area chart to track changes over time (e.g., total healthcare costs vs. state health expenditure over the years).

***Geospatial Representation***
- A choropleth (map) visualization to show state-wise variations in health expenditure and healthcare-related metrics.

***Demographics & Healthcare Utilization***
- A bar chart or heatmap to break down demographic factors like age, income, employment, and health conditions influencing healthcare costs.

## Beds per Pop DF

In [3]:
df = pd.read_csv('DQS_Community_hospital_beds__by_state__United_States_20250120.csv')
df.head()

,TOPIC,SUBTOPIC,SUBTOPIC_ID,CLASSIFICATION,CLASSIFICATION_ID,GROUP,GROUP_ID,GROUP_ORDER,SUBGROUP,SUBGROUP_ID,SUBGROUP_ORDER,ESTIMATE_TYPE,ESTIMATE_TYPE_ID,TIME_PERIOD,TIME_PERIOD_ID,ESTIMATE,STANDARD_ERROR,FLAG,FOOTNOTE_ID_LIST,STATE_FIPS
0,Community hospital beds,NaN,NaN,Total,0,Total,0,0,United States,0,0,"Beds per 1,000 resident population",1,1980,1,4.5,NaN,NaN,"FN0466,NT0064,SC0056,NT9999",0
1,Community hospital beds,NaN,NaN,Total,0,Total,0,0,United States,0,0,"Beds per 1,000 resident population",1,1990,2,3.7,NaN,NaN,"FN0466,NT0064,SC0056,NT9999",0
2,Community hospital beds,NaN,NaN,Total,0,Total,0,0,United States,0,0,"Beds per 1,000 resident population",1,2000,3,2.9,NaN,NaN,"FN0466,NT0064,SC0056,NT9999",0
3,Community hospital beds,NaN,NaN,Total,0,Total,0,0,United States,0,0,"Beds per 1,000 resident population",1,2009,4,2.6,NaN,NaN,"FN0466,NT0064,SC0056,NT9999",0
4,Community hospital beds,NaN,NaN,Total,0,Total,0,0,United States,0,0,"Beds per 1,000 resident population",1,2010,5,2.6,NaN,NaN,"FN0466,NT0064,SC0056,NT9999",0

In [7]:
df = df[df.TIME_PERIOD==2020]

In [36]:
bed_df = df[['SUBGROUP','ESTIMATE']].rename({'SUBGROUP':'STATE',
                                             'ESTIMATE':'BEDS_PER_1000_POPULATION'})

bed_df.to_csv('beds_per_population.csv')

bed_df.head()

         SUBGROUP  ESTIMATE
11  United States       2.4
23        Alabama       3.1
35         Alaska       2.2
47        Arizona       1.9
59       Arkansas       3.1

In [12]:
df.head().T

,0,1,2,3,4
caseorder,1,2,3,4,5
customer_id,C412403,Z919181,F995323,A879973,C544523
interaction,8cd49b13-f45a-4b47-a2bd-173ffa932c2f,d2450b70-0337-4406-bdbb-bc1037f1734c,a2057123-abf5-4a2c-abad-8ffe33512562,1dec528d-eb34-4079-adce-0d7a40e82205,5885f56b-d6da-43a3-8760-83583af94266
uid,3a83ddb66e2ae73798bdf1d705dc0932,176354c5eef714957d486009feabf195,e19a0fa00aeda885b8a436757e889bc9,cd17d7b6d152cb6f23957346d11c3f07,d2f0425877b10ed6bb381f3e2579424a
city,Eva,Marianna,Sioux Falls,New Richland,West Point
state,Alabama,Florida,South Dakota,Minnesota,Virginia
county,Morgan,Jackson,Minnehaha,Waseca,King William
zip,35621,32446,57110,56072,23181
lat,34.3496,30.84513,43.54321,43.89744,37.59894
lng,-86.72508,-85.22907,-96.63772,-93.51479,-76.88958
population,2951,11303,17125,2162,5287
area,Suburban,Urban,Suburban,Suburban,Rural
timezone,America/Chicago,America/Chicago,America/Chicago,America/Chicago,America/New_York
job,"Psychologist, sport and exercise",Community development worker,Chief Executive Officer,Early years teacher,Health promotion specialist
children,1,3,3,0,1
age,53,51,53,78,22
income,86575.93,46805.99,14370.14,39741.49,1209.56
marital,Divorced,Married,Widowed,Married,Widowed
gender,Male,Female,Female,Male,Female
readmis,No,No,No,No,No
vitd_levels,19.141466,18.940352,18.057507,16.576858,17.439069
doc_visits,6,4,4,4,5
full_meals_eaten,0,2,1,1,0
vitd_supp,0,1,0,0,2
soft_drink,No,No,No,No,Yes
initial_admin,Emergency Admission,Emergency Admission,Elective Admission,Elective Admission,Elective Admission
highblood,Yes,Yes,Yes,No,No
stroke,No,No,No,Yes,No
complication_risk,Medium,High,Medium,Medium,Low
overweight,No,Yes,Yes,No,No
arthritis,Yes,No,No,Yes,No
diabetes,Yes,No,Yes,No,No
hyperlipidemia,No,No,No,No,Yes
backpain,Yes,No,No,No,No
anxiety,Yes,No,No,No,No
allergic_rhinitis,Yes,No,No,No,Yes
reflux_esophagitis,No,Yes,No,Yes,No
asthma,Yes,No,No,Yes,No
services,Blood Work,Intravenous,Blood Work,Blood Work,CT Scan
initial_days,10.58577,15.129562,4.772177,1.714879,1.254807
totalcharge,3726.70286,4193.190458,2434.234222,2127.830423,2113.073274
additional_charges,17939.40342,17612.99812,17505.19246,12993.43735,3716.525786
item1,3,3,2,3,2
item2,3,4,4,5,1
item3,2,3,4,5,3
item4,2,4,4,3,3
item5,4,4,3,4,5
item6,3,4,4,5,3
item7,3,3,3,5,4
item8,4,3,3,5,3
spending_per_capita,9280.0,9865.0,12495.0,10846.0,9195.0

In [23]:
df.doc_visits.describe()

count    10000.000000
mean         5.012200
std          1.045734
min          1.000000
25%          4.000000
50%          5.000000
75%          6.000000
max          9.000000
Name: doc_visits, dtype: float64

In [15]:
import pprint

In [24]:
df.shape

(10000, 51)

In [29]:
df[df.state=='Virginia'].population.mean()

9023.700348432056

In [31]:
df[df.state=='California'].population.mean()

21764.556363636362

In [33]:
df.initial_days.describe()

count    10000.000000
mean        34.455299
std         26.309341
min          1.001981
25%          7.896215
50%         35.836244
75%         61.161020
max         71.981490
Name: initial_days, dtype: float64